### ISSUE TITLE
Go server says not all attributes present when doing combined issue/disclose

### ISSUE THREAD

**Issue by woutslakhorst** [privacybydesign/irmago#36]
When doing a combined issue/disclose the go server gives an error that not all attributes were present, but the phone said they were. For the disclose part, the attributes are not set to values. (Used for logging puporses)

Stacktrace below
```
[2019-04-16T10:53:50+02:00]  WARN Sending session error description=Not all requested-for attributes were present error=ATTRIBUTES_MISSING message= status=400
[2019-04-16T10:53:50+02:00]  WARN goroutine 309 [running]:
runtime/debug.Stack(0xc4201c57a0, 0x164f9f7, 0x15)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/privacybydesign/irmago/server.RemoteError(0x164d447, 0x12, 0x190, 0x16600fc, 0x2d, 0x0, 0x0, 0x0)
	/Users/wout.slakhorst/go/src/github.com/privacybydesign/irmago/server/api.go:137 +0x43f
github.com/privacybydesign/irmago/internal/servercore.(*session).fail(0xc4202beea0, 0x164d447, 0x12, 0x190, 0x16600fc, 0x2d, 0x0, 0x0, 0xc4204b5668)
	/Users/wout.slakhorst/go/src/github.com/privacybydesign/irmago/internal/servercore/helpers.go:44 +0x66
github.com/privacybydesign/irmago/internal/servercore.(*session).handlePostCommitments(0xc4202beea0, 0xc4204f0b20, 0x1e00, 0x1586960, 0xc4204f0b20, 0x0)
	/Users/wout.slakhorst/go/src/github.com/privacybydesign/irmago/internal/servercore/handle.go:100 +0xe3e
github.com/privacybydesign/irmago/internal/servercore.(*Server).HandleProtocolMessage(0xc4202644e0, 0xc420026a46, 0x25, 0xc420026a40, 0x4, 0xc4203e0de0, 0xc420572000, 0x12bf, 0x1e00, 0x0, ...)
	/Users/wout.slakhorst/go/src/github.com/privacybydesign/irmago/internal/servercore/api.go:364 +0x10b8
github.com/privacybydesign/irmago/server/irmaserver.(*Server).HandlerFunc.func1(0x16c2d00, 0xc4203409a0, 0xc4206b2400)
	/Users/wout.slakhorst/go/src/github.com/privacybydesign/irmago/server/irmaserver/main.go:141 +0x12f
net/http.HandlerFunc.ServeHTTP(0xc4201a0570, 0x16c2d00, 0xc4203409a0, 0xc4206b2400)
	/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:1947 +0x44
github.com/privacybydesign/irmago/vendor/github.com/go-chi/chi.(*Mux).Mount.func1(0x16c2d00, 0xc4203409a0, 0xc4206b2400)
	/Users/wout.slakhorst/go/src/github.com/privacybydesign/irmago/vendor/github.com/go-chi/chi/mux.go:291 +0x107
net/http.HandlerFunc.ServeHTTP(0xc42037e360, 0x16c2d00, 0xc4203409a0, 0xc4206b2400)
	/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:1947 +0x44
github.com/privacybydesign/irmago/vendor/github.com/go-chi/chi.(*Mux).routeHTTP(0xc4201c4780, 0x16c2d00, 0xc4203409a0, 0xc4206b2400)
	/Users/wout.slakhorst/go/src/github.com/privacybydesign/irmago/vendor/github.com/go-chi/chi/mux.go:424 +0x289
github.com/privacybydesign/irmago/vendor/github.com/go-chi/chi.(*Mux).(github.com/privacybydesign/irmago/vendor/github.com/go-chi/chi.routeHTTP)-fm(0x16c2d00, 0xc4203409a0, 0xc4206b2400)
	/Users/wout.slakhorst/go/src/github.com/privacybydesign/irmago/vendor/github.com/go-chi/chi/mux.go:368 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4201a0580, 0x16c2d00, 0xc4203409a0, 0xc4206b2400)
	/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:1947 +0x44
github.com/privacybydesign/irmago/vendor/github.com/go-chi/cors.(*Cors).Handler.func1(0x16c2d00, 0xc4203409a0, 0xc4206b2400)
	/Users/wout.slakhorst/go/src/github.com/privacybydesign/irmago/vendor/github.com/go-chi/cors/cors.go:199 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc42037e380, 0x16c2d00, 0xc4203409a0, 0xc4206b2400)
	/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:1947 +0x44
github.com/privacybydesign/irmago/vendor/github.com/go-chi/chi.(*Mux).ServeHTTP(0xc4201c4780, 0x16c2d00, 0xc4203409a0, 0xc4201a2400)
	/Users/wout.slakhorst/go/src/github.com/privacybydesign/irmago/vendor/github.com/go-chi/chi/mux.go:81 +0x221
net/http.serverHandler.ServeHTTP(0xc420162a90, 0x16c2d00, 0xc4203409a0, 0xc4201a2400)
	/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4204e0140, 0x16c3340, 0xc420532580)
	/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:2795 +0x27b
```

**Comment by sietseringers** [comment]
This doesn't seem to happen for all combined sessions, can you show the session request?

**Comment by woutslakhorst** [comment]
```json
{
  "timeout": 120, 
  "validity": 120, 
  "request" : {
    "type":"issuing", 
    "credentials": [
      {
        "credential":"irma-demo.nuts.agb", 
        "attributes" : {
          "role":"Doktersasistent", 
          "agbcode":"00000007"
         }
      }
    ], 
    "disclose" : [
      {
        "label":"Initialen", 
        "attributes":["pbdf.nijmegen.personalData.initials"]
      }, 
      {
        "label":"Achternaam", 
        "attributes" : ["pbdf.nijmegen.personalData.familyname"] 
      }, 
      {
        "label":"Geboortedatum", 
        "attributes":["pbdf.nijmegen.personalData.dateofbirth"]
      }
    ]
  }
}
```
